version: '3.3'

services:
  sports-challenger:
    build:
      context: .
      dockerfile: Dockerfile
    image: sports-challenger
    container_name: pgcard.flashmobile.id
    restart: always
    ports:
      - 0.0.0.0:9000:9000
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      - sports-challenger-net

networks:
  sports-challenger-net:
    name: sports-challenger-net
