package consts

const (
	ASCII_UPPER_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	ASCII_LOWER_CHARS = "abcdefghijklmnopqrstuvwxyz"
	ASCII_LETTERS     = ASCII_UPPER_CHARS + ASCII_LOWER_CHARS
	ASCII_DIGITS      = "0123456789"
	ASCII_NO_SYMBOL   = ASCII_DIGITS + ASCII_LETTERS
)
